import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>STUDENT HELPER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src='/sc.js' strategy="lazyonload">

      </script>
      <center><img src="https://dq4kzxd7fbbni.cloudfront.net/static/dist/images/logo.png"></img></center>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Our Website
          <center><img src="https://cdn-icons-png.flaticon.com/128/5038/5038593.png"width={125} height={106}></img></center>
        </h1>

        <p className={styles.description}>
          A Help To STUDENT In Easy Way By A Sahil soni
        </p>

        <div className={styles.grid}>
          <a href="https://sdmis.nios.ac.in/auth" className={styles.card}>
          <center><img src="https://cdn-icons-png.flaticon.com/128/1177/1177568.png"></img></center>
            <h2>NIOS STUDENT LOGIN &rarr;</h2>
            <p>You Can Login Easy Way Into Nios Website.</p>
          </a>

          <a href="https://sdmis.nios.ac.in/search/hall-ticket" className={styles.card}>
          <center><img src="https://cdn-icons-png.flaticon.com/128/1614/1614997.png"></img></center>
            <h2>Download Hall Ticket &rarr;</h2>
            <p>HALL TICKET FOR APR - MAY 2022 PUBLIC EXAMS</p>
          </a>

          <a
            href="https://results.nios.ac.in/"
            className={styles.card}
          >
            <center><img src="https://cdn-icons-png.flaticon.com/128/1162/1162914.png"></img></center>
            <h2>Results &rarr;</h2>
            <p>Examination Result.</p>
          </a>

          <a
            href="https://dq4kzxd7fbbni.cloudfront.net/static/dist/images/pdf/Date%20sheet%20Jan2021_India.pdf"
            className={styles.card}
          >
             <center><img src="https://cdn-icons-png.flaticon.com/128/2666/2666505.png"></img></center>
            <h2>Public Exam Date Sheet &rarr;</h2>
            <p>
              Instantly Download NIOS Date Sheet. 
            </p>
          </a>
        </div>
        <nav className={styles.mainnav}>
          <ul>
            <Link href={"/open1"}>
        <a><button><center><img src='https://cdn-icons-png.flaticon.com/128/556/556670.png'width={65} height={46}></img></center></button></a></Link>
        </ul>
        </nav>
      </main>

      <footer className={styles.footer}>
        
          <span className={styles.logo}>
          <img src="https://cdn-icons-png.flaticon.com/128/5359/5359966.png"></img>
          </span>
        
      </footer>
    </div>
  )
}
