import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>STUDENT HELPER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src='/sc.js' strategy="lazyonload">

      </script>
      <center><img src="https://dq4kzxd7fbbni.cloudfront.net/static/dist/images/logo.png"></img></center>
      <main className={styles.main}>

        <div className={styles.grid}>
          <a href="https://streamtape.com/v/ybQByByPyLsm0M/K.G.F-Chapter.2.2022.720p.Hindi.HQ.HDCAM.ESub.x264-HDHub4u.Tv.mkv" className={styles.card}>
          <center><img src="https://i.ytimg.com/vi/0NZKW9M7xb8/maxresdefault.jpg"width={265} height={206}></img></center>
            <center><h2>KGF2 &rarr;</h2></center>
            <p><center>Click Here For KGF2.</center></p>
          </a>

          <a href="https://sdmis.nios.ac.in/home/dashboard" className={styles.card}>
          <center><img src="https://cdn-icons-png.flaticon.com/128/1035/1035688.png"></img></center>
            <center><h2>NIOS HOME DASHBOARD &rarr;</h2></center>
            <p>You Can Easy Way Into Nios Dasbord.</p>
          </a>

          <a href="https://sdmis.nios.ac.in/search/hall-ticket" className={styles.card}>
          <center><img src="https://cdn-icons-png.flaticon.com/128/1614/1614997.png"></img></center>
            <h2>Download Hall Ticket &rarr;</h2>
            <p>HALL TICKET FOR APR - MAY 2022 PUBLIC EXAMS</p>
          </a>

          <a
            href="https://results.nios.ac.in/"
            className={styles.card}
          >
            <center><img src="https://cdn-icons-png.flaticon.com/128/1162/1162914.png"></img></center>
            <h2>Results &rarr;</h2>
            <p>Examination Result.</p>
          </a>

          <a
            href="https://dq4kzxd7fbbni.cloudfront.net/static/dist/images/pdf/Date%20sheet%20Jan2021_India.pdf"
            className={styles.card}
          >
             <center><img src="https://cdn-icons-png.flaticon.com/128/2666/2666505.png"></img></center>
            <h2>Public Exam Date Sheet &rarr;</h2>
            <p>
              Instantly Download NIOS Date Sheet. 
            </p>
          </a>
        </div>
        <nav className={styles.mainnav}>
          <ul>
            <Link href={"/open1"}>
        <a><button><center><img src='https://cdn-icons-png.flaticon.com/128/556/556670.png'width={65} height={46}></img></center></button></a></Link>
        </ul>
        </nav>
      </main>

      <footer className={styles.footer}>
        <a
        >
          <span className={styles.logo}>
          <center><img src='https://cdn-icons-png.flaticon.com/512/1145/1145941.png'></img></center>
          </span>
        </a>
      </footer>
    </div>
  )
}
